### PR TITLE
Hides custom Firefox titlebar buttonbox to match Win11 ones

### PR DESCRIPTION
**Pull request by Marocco2**
Hides custom Firefox titlebar buttonbox to match Win11 ones and also bring Mica effect to buttonbox

### CODE REVIEW

**Comment by QNetITQ** [comment]
Fitting element highlights to background elements is not easy. But I got the point. I implement this a little in my own way. There are certain difficulties.

**Comment by Marocco2** [comment]
> Fitting element highlights to background elements is not easy. But I got the point. I implement this a little in my own way. There are certain difficulties.

Yeah sure, no problem

**Comment by QNetITQ** [comment]
I have explored the ability to mimic native window control buttons. Imitation of system buttons is possible only approximately, but not exactly. At a detailed look, it will be noticeable that these are not system elements. In this regard, I decided to leave it as it is.

**Comment by Marocco2** [comment]
> I have explored the ability to mimic native window control buttons. Imitation of system buttons is possible only approximately, but not exactly. At a detailed look, it will be noticeable that these are not system elements. In this regard, I decided to leave it as it is.

Fair enough

**Pull request closed without merging**
